version: '3.8'

services:
  frontend:
    build: .
    container_name: meet_frontend
    ports:
      - "80:80"
    depends_on:
      - signaling

  signaling:
    build:
      context: ./server
    container_name: meet_signaling
    ports:
      - "5000:5000"
    command: node index.js
